#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: ipympi <command>"
  exit 1
fi

if [ -z $OMPI_COMM_WORLD_SIZE ]; then
  echo "Cannot see MPI world, are you using mpirun?"
  exit 1
fi

ID=$OMPI_COMM_WORLD_RANK
NNODES=$OMPI_COMM_WORLD_SIZE

if [ $NNODES -lt 3 ]; then
  echo "Error: 3 cpu minimum (1 app, 1 controller, 1 engine)"
  exit 1
fi

# Run the actual program in node 0
if [ $ID -eq 0 ]; then
    echo "Running $1 on cpu $ID"
    sleep 10
    $1 2>&1 > ${1}.log

elif [ $ID -eq 1 ]; then
    echo "Running ipcontroller on cpu $ID"
    ipcontroller --ip="*" 2>&1 > ipcontroller.log

else
    ENGINEID=$((ID - 2))
    echo "Running ipengine $ENGINEID on cpu $ID"
    sleep 5
    ipengine 2>&1 > ipengine_${ENGINEID}.log
fi 
