
features:
  - name: my features 1
    type: ordinal
    files:
      # - path: /path/to/GA_data/GA-cover2/Th_v1.tif
      # - list: /path/to/GA_data/GA_Cover2_sirsam_LLC/sirsam_covariates_convolved.txt
      - directory: /path/to/GA_data/GA-cover2
    # transforms are performed in order
    transforms:
      - centre
      - standardise
    imputation: none

  - name: my features 2
    type: categorical
    files:
      # - path: /path/to/GA_data/GA-cover2/Th_v1.tif
      # - list: /path/to/csv_file.csv
      - directory: /path/to/GA_data/GA-cover2/cat_datasets
    # transforms are performed in order
    transforms:
      - randomhot:
          n_features: 10
          seed: 1
    imputation: none

# mask file used for masking prediction grid
# Mask with values=retain will be predicted
mask:
  file: /path/to/GA_data/GA-cover2/mask/old_mask_test.tif
  retain: 1

preprocessing:
  # imputation: none
  # imputation: gaus
  # imputation: nn
  imputation: mean

  transforms:
    # - whiten:
        # keep_fraction: 0.8

targets:
  file: /path/to/GA_data/GA-cover2/geochem_sites.shp
  property: K_ppm_imp_

clustering:
  file: /path/to/GA_data/GA-cover2/geochem_sites_class1.shp
  property: class
  algorithm: kmeans
  arguments:
    n_classes: 12
    oversample_factor: 5

prediction:
  quantiles: 0.95

validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: .
