features:
  - type: ordinal
    files:
      - directory: $UNCOVERML_SRC/tests/test_data/sirsam/covariates/
    transforms:
      - standardise
    imputation: mean

clustering:
    
  # Semi-supervised learning can be performed by providing a #
  # shapefile containing class-labelled points.              #

  #file: /path/to/class_labels.shp
  #property: name_of_class_label_property
 
  n_classes: 5
  oversample_factor: 5

validation:
  feature_rank: True
  k-fold:
    parallel: True
    folds: 5
    random_seed: 1

prediction:
  quantiles: 0.95
  outbands: 1

output:
  directory: ./kmeans_out
