
experiment: my_run
patchsize: 0
memory_fraction: 0.5

features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
      - path: configs/data/sirsam/relief_apsect.tif
    transforms:
      - standardise
      - whiten:
          keep_fraction: 0.8
    imputation: none

preprocessing:
  imputation: none
  transforms:
    - whiten:
        keep_fraction: 0.8

targets:
  file: configs/data/geochem_sites.shp
  property: K_ppm_imp
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: transformedrandomforest
  arguments:
    n_estimators: 10
    target_transform: identity
    random_state: 1
    max_depth: 20
  optimisation:
    searchcv_params:
      n_iter: 6
      cv: 2
      verbose: 1000
      n_points: 3
      n_jobs: 6
    params_space:
      'max_depth': Integer(1, 15)
      'n_estimators': Integer(10, 100)
      'max_features': Categorical(['auto', 'sqrt', 'log2'])
      'min_samples_split': Integer(2, 50)
      'min_samples_leaf': Integer(1, 50)
      'min_weight_fraction_leaf': Real(0.0, 0.5, prior='uniform')


prediction:
  quantiles: 0.95
  outbands: 4


validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: rf/
  model: rf.model

