
experiment: my_run
patchsize: 0
memory_fraction: 0.5

features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
      - path: configs/data/sirsam/relief_apsect.tif
    transforms:
#      - standardise
#      - whiten:
#          keep_fraction: 0.8
    imputation: none

preprocessing:
  imputation: none
  transforms:
#    - whiten:
#        keep_fraction: 0.8

targets:
  file: configs/data/geochem_sites_cropped.shp
  property: K_ppm_imp
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: lgbm
  arguments:
    n_estimators: 10
    target_transform: identity
    random_state: 1
    max_depth: 20
  optimisation:
    hyperopt_params:
      max_evals: 5
      step: 2
      cv: 2
      verbose: true
      random_state: 3
      scoring: r2  # r2, neg_mean_absolute_error, etc..see note above
      algo: bayes   # bayes, or anneal
    hp_params_space:
      max_depth: randint('max_depth', 1, 15)
      n_estimators: randint('n_estimators', 5, 25)
      learning_rate: loguniform('learning_rate', -5, 0)
      num_leaves: randint('num_leaves', 5, 100)
      subsample_for_bin: randint('subsample_for_bin', 5, 1000000)
      colsample_bytree: uniform('colsample_bytree', 0.01, 1.0)
      min_child_weight: uniform('min_child_weight', 0, 10)
      min_child_samples: randint("min_child_samples", 2, 100)
      min_gain_to_split: loguniform('min_gain_to_split', -5, 0)
      min_data_in_leaf: randint("min_data_in_leaf", 200, 10000)
      feature_fraction: uniform("feature_fraction", 0.2, 0.95)
      reg_alpha: uniform("reg_lambda", 0, 1)
      reg_lambda: uniform("reg_lambda", 0, 1)

#      max_features: choice('max_features', ['auto', 'sqrt', 'log2'])
#      min_samples_split: randint('min_samples_split', 2, 50)
#      min_samples_leaf: randint('min_samples_leaf', 1, 50)
#      min_weight_fraction_leaf: uniform('min_weight_fraction_leaf', 0.0, 0.5)
#      max_leaf_nodes: randint('max_leaf_nodes', 10, 50)


prediction:
  prediction_template: configs/data/sirsam/dem_foc2.tif
  quantiles: 0.95
  outbands: 4


validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: lgbm/
#  model:

