experiment: my_run
patchsize: 0
memory_fraction: 0.5

features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
      - path: configs/data/sirsam/relief_apsect.tif
    transforms:
      - identity
#      - whiten:
#          keep_fraction: 0.8
    imputation: none

preprocessing:
  imputation: none
  transforms:
    - whiten:
        keep_fraction: 0.8

targets:
  file: configs/data/geochem_sites.shp
  property: K_ppm_imp
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: quantilegb
  arguments:
    mean_model_params:
        n_estimators: 10
    upper_quantile_params:
        alpha: 0.95
        n_estimators: 10
    lower_quantile_params:
        alpha: 0.05
        n_estimators: 10

prediction:
  quantiles: 0.95
  outbands: 4


validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 2
      random_seed: 1

output:
  directory: qxgb/
  model: xgboost.model

