
experiment: my_run
patchsize: 0
memory_fraction: 0.5

features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
      - path: configs/data/sirsam/relief_apsect.tif
    transforms:
      - standardise
      - whiten:
          keep_fraction: 0.8
    imputation: none

preprocessing:
  imputation: none
  transforms:
    - whiten:
        keep_fraction: 0.8

targets:
  file: configs/data/geochem_sites.shp
  property: K_ppm_imp
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: xgboost
  arguments:
    target_transform: identity

prediction:
  quantiles: 0.95
  outbands: 1


validation:
  #- feature_rank
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: out/
  model: xgboost.model

