
experiment: my_run
patchsize: 0
memory_fraction: 0.5

#intersected_features:
#  "relief_apsect.tif": "relief4"
#  "LATITUDE_GRID1.tif": "latitude"
#  "LONGITUDE_GRID1.tif": "longitude"
#  "er_depg.tif": "er_depg"
#  "sagawet_b_sir.tif": "sagawet"
#  "dem_foc2.tif": "dem_foc2"
#  "outcrop_dis2.tif": "outcrop"
#  "k_15v5.tif": "k_15v5"


features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/relief_apsect.tif
      - path: configs/data/sirsam/LATITUDE_GRID1.tif
      - path: configs/data/sirsam/LONGITUDE_GRID1.tif
    transforms:
      - identity
#      - whiten:
#          keep_fraction: 0.98
    imputation: none
  - name: my 2nd continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
    transforms:
      - identity
    #      - whiten:
    #          keep_fraction: 0.98
    imputation: none

preprocessing:
  imputation: none
  transforms:
#    - whiten:
#        keep_fraction: 0.98

targets:
#  file: configs/data/geochem_sites.shp
  file: configs/data/sirsam/out_resampled/geochem_sites.shp
  property: K_ppm_imp
  weight_col_name: K_ppm_imp_  # hack weight col
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: svrmulti
  arguments:
    target_transform: identity
    sampling_fraction: 0.8


prediction:
  quantiles: 0.95
  outbands: 4

validation:
#  - feature_rank
  - parallel
  - k-fold:
      folds: 5
      random_seed: 1

output:
  directory: svr/
