
experiment: my_run
patchsize: 0
memory_fraction: 0.5

features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
      - path: configs/data/sirsam/relief_apsect.tif
      - path: configs/data/sirsam/LATITUDE_GRID1.tif
      - path: configs/data/sirsam/LONGITUDE_GRID1.tif
    transforms:
      - identity
#      - whiten:
#          keep_fraction: 0.98
    imputation: none

preprocessing:
  imputation: none
  transforms:
#    - whiten:
#        keep_fraction: 0.98

targets:
  file: configs/data/geochem_sites.shp
  property: K_ppm_imp
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: xgbquantileregressor
  arguments:
    target_transform: standardise
    alpha: 0.95
    delta: 1.0
    thresh: 6.0
    variance: 3.2
    n_estimators: 5

prediction:
  quantiles: 0.95
  outbands: 1

validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 2
      random_seed: 1

output:
  directory: xgb_upper/
