
experiment: my_run
patchsize: 0
memory_fraction: 0.5

intersected_features:
  "relief_apsect.tif": "relief4"
  "LATITUDE_GRID1.tif": "latitude"
  "LONGITUDE_GRID1.tif": "longitude"
  "er_depg.tif": "er_depg"
  "sagawet_b_sir.tif": "sagawet"
  "dem_foc2.tif": "dem_foc2"
  "outcrop_dis2.tif": "outcrop"
  "k_15v5.tif": "k_15v5"


features:
  - name: my continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/relief_apsect.tif
      - path: configs/data/sirsam/LATITUDE_GRID1.tif
      - path: configs/data/sirsam/LONGITUDE_GRID1.tif
    transforms:
      - identity
#      - whiten:
#          keep_fraction: 0.98
    imputation: none
  - name: my 2nd continuous features
    type: continuous
    files:
      - path: configs/data/sirsam/er_depg.tif
      - path: configs/data/sirsam/sagawet_b_sir.tif
      - path: configs/data/sirsam/dem_foc2.tif
      - path: configs/data/sirsam/outcrop_dis2.tif
      - path: configs/data/sirsam/k_15v5.tif
    transforms:
      - identity
    #      - whiten:
    #          keep_fraction: 0.98
    imputation: none

preprocessing:
  imputation: none
  transforms:
#    - whiten:
#        keep_fraction: 0.98

targets:
#  file: configs/data/geochem_sites.shp
  file: out_resampled/geochem_sites.shp
  property: K_ppm_imp
  weight_col_name: K_ppm_imp_  # hack weight col
#  group_targets:
#    groups_eps: 0.09

learning:
  algorithm: gradientboost
  arguments:
    target_transform: identity
    loss: 'ls'
    max_depth: 20
    learning_rate: 0.1
    n_estimators: 100
    subsample: 0.9
    min_samples_split: 2
    min_samples_leaf: 2
    min_weight_fraction_leaf: 0.0
    max_features: "auto"
    alpha: 0.95
    random_state: 3
  optimisation:
    searchcv_params:
      n_iter: 6
      cv: 2
      verbose: 1000
      n_points: 3
      n_jobs: 6
    params_space:
      'max_depth': Integer(1, 15)
      'learning_rate': Real(10 ** -5, 10 ** 0, prior="log-uniform")
      'n_estimators': Integer(10, 100)
      'subsample': Real(0.01, 1.0, prior='uniform')
      'max_features': Categorical(['auto', 'sqrt', 'log2'])
      'min_samples_split': Integer(2, 50)
      'min_samples_leaf': Integer(1, 50)
      'min_weight_fraction_leaf': Real(0.0, 0.5, prior='uniform')
      'max_leaf_nodes': Integer(10, 50)

prediction:
#  corner_coordinates:
#    upper_left: ( 119.9670000, -26.9553333)
#    lower_right: ( 121.5253333, -28.0170000)
  quantiles: 0.95
  outbands: 1

validation:
  #- feature_rank
  - parallel
  - k-fold:
      folds: 3
      random_seed: 1

output:
  directory: xgb_upper/


"dem_fill.tif": "dem_fill",
"mrvbf_9.tif": "mrvbf_9",
"Rad2016K_Th.tif": "Rad2016K",
"s2-dpca-85m_band1.tif": "s2_band1",
"s2-dpca-85m_band2.tif": "s2_band2",
"s2-dpca-85m_band3.tif": "s2_band3",
"Thorium_2016.tif": "Thorium",
"relief_radius4.tif": "relief",
"be-30y-85m-avg-ND-RED-BLUE.filled.lzw.nodata.tif": "be_1",
"SagaWET9cell_M.tif": "SagaWET",
"3dem_mag0_finn.tif": "3dem_mag",
"be-30y-85m-avg-SWIR1.filled.lzw.nodata.tif": "be_2",
"water-85m_1.tif": "water",
"3dem_mag2.tif": "3dem_mag2",
"be-30y-85m-avg-ND-SWIR1-NIR.filled.lzw.nodata.tif": "be_3",
"si_geol1.tif": "si_geol1",
"Clim_Prescott_LindaGregory.tif": "Clim",
"be-30y-85m-avg-CLAY-PC2.filled.lzw.nodata.tif": "be_4",
"be-30y-85m-avg-GREEN.filled.lzw.nodata.tif": "be_5",
"be-30y-85m-avg_BLUE+SWIR2.tif": "be_6",
"national_Wii_RF_multirandomforest_prediction.tif": "rf_pred",
"ceno_euc_aust1.tif": "ceno_eu",
"3dem_mag1_fin.tif": "3dem_mag",
"Potassium_2016.tif": "Potassi",
"Dose_2016.tif": "Dose_2016",
"Gravity_land.tif": "Gravity",
"Uranium_2016.tif": "Uranium",
"Geol_major.tif": "Geol_major"