#  when undersample == false, we choose all points without replacement, i.e., downsampling is not allowed
#  when undersample == true, we choose points with or without bootstrap

targets:
  file: configs/data/sirsam/out_resampled/geochem_sites.shp
  property: K_ppm_imp
  resample:
#    spatial:
#      undersample: false
#      rows: 10
#      cols: 10
#      bootstrap: True
#      output_samples: 4000
    value:
      undersample: false
      bins: 10
      bootstrap: False
      output_samples: 100
      interval: percentile
      validation: True
      validation_points: 10

output:
  directory: ./resampling_out

