learning:
  algorithm: randomforest
  arguments:
    n_estimators: 10
    target_transform: log
    random_state: 1

features:
  - type: ordinal
    # Use fields in the 'targets' shapefile as covariates
    shapefile:
      file: $UNCOVERML_SRC/tests/test_data/sirsam/targets/geochem_sites_log.shp 
      fields:
       - Al_ppm_imp
       - As_ppm_imp
       - Ba_ppm_imp
       - Be_ppm_imp
       - Ca_ppm_imp
       - Ce_ppm_imp
       - Co_ppm_imp
       - Cr_ppm_imp
       - Cu_ppm_imp
      ndv: None
    transforms:
      - centre
      - standardise
    imputation: mean

targets:
  file: $UNCOVERML_SRC/tests/test_data/sirsam/targets/geochem_sites_log.shp
  property: Na_ppm_imp
  # Drop rows that have this value in the 'property' column. These rows
  # won't be used in training.
  drop: [0.5]

validation:
    k-fold:
      parallel: True
      folds: 5
      random_seed: 1

prediction:
  quantiles: 0.95
  outbands: 4

output:
  directory: ./tabular_out

  # By default, model file will be saved in output directory.            #
  # Model can be saved to a specific path if desired, and different      #
  # model files can be loaded for the prediction step if specified here. #

  plot_feature_ranks: True
  plot_intersection: True
  plot_real_vs_pred: True
  plot_correlation: True
  plot_target_scaling: True
  
  #pickling:
  #  covariates: ./random_forest_out/features.pk
  #  targets: ./random_forest_out/targets.pk

