learning:
  algorithm: transformedrandomforest
  target_search: True
  target_search_threshold: 0.7
  target_search_extents:
      xmin: 120.302
      ymin: -27.821
      xmax: 120.672
      ymax: -27.275

  arguments:
    n_estimators: 10
    target_transform: identity
    forests: 20
    parallel: True
    random_state: 1

features:
  - type: ordinal
    files:
      - directory: $UNCOVERML_SRC/tests/test_data/sirsam/covariates/
    transforms:
      - centre
      - standardise
    imputation: mean

targets:
  file: $UNCOVERML_SRC/tests/test_data/sirsam/targets/geochem_sites_log.shp
  property: Na_ppm_imp

validation:
  k-fold:
    parallel: True
    folds: 5
    random_seed: 1

prediction:
  quantiles: 0.95
  outbands: 4

output:
  directory: ./target_search_out

