learning:
  algorithm: multirandomforest
  arguments:
    n_estimators: 10
    target_transform: log
    forests: 20
    parallel: True
    random_state: 1

features:
  - type: ordinal
    files:
      - directory: 'C:\path\to\uncoverml\uncover-ml\tests\test_data\sirsam\covariates'
    transforms:
      - centre
      - standardise
    imputation: mean

targets:
  file: 'C:\path\to\uncoverml\tests\test_data\sirsam\targets\geochem_sites_log.shp'
  property: Na_ppm_imp

validation:
  feature_rank: True
  k-fold:
    parallel: True
    folds: 5
    random_seed: 1

prediction:
  quantiles: 0.95
  outbands: 4

output:
  directory: 'C:\path\to\uncover-ml\random_forest_out'

  # By default, model file will be saved in output directory.            #
  # Model can be saved to a specific path if desired, and different      #
  # model files can be loaded for the prediction step if specified here. #

  model: 'C:\path\to\uncover-ml\random_forest_out\random_forest.model'

  plot_feature_ranks: True
  plot_intersection: True
  plot_real_vs_pred: True
  plot_correlation: True
  plot_target_scaling: True